name: iml
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - pandas
  - matplotlib
  - missingno
  - scikit-learn
  - seaborn
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - tensorboard
  - xgboost

