name: iml
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - pandas
  - matplotlib
  - missingno
  - scikit-learn
  - seaborn
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - tensorboard
  - xgboost
  - tqdm
  - ipywidgets
  - imbalanced-learn
  - keras
  - pip
  - pip:
      - tensorflow_addons
      - opencv-python
      - itertools
